#! /usr/bin/env bash

echoerr() { echo "$@" 1>&2; }

quiet='false'
nodl='false'

while getopts ':qn' flag; do
	case "${flag}" in
		q) quiet='true' ;;
		n) nodl='true' ;;
		*) echoerr "Illegal option: -${OPTARG}"; echoerr "Quitting." ; exit ;;
	esac
done

# Change directory to source
cd $(dirname "$(readlink -f "$0")")
if [ "$nodl" = 'false' ]; then
	if [ "$quiet" = 'false' ]; then
		echo 'Downloading from drive...'
	fi
	python dl.py
	if [ "$?" = '0' ]; then
		if [ "$quiet" = 'false' ]; then
			echo 'Download successful.'
		fi
	else
		echoerr 'Download failed. Quitting.'
		exit
	fi
fi
python mus.py $quiet